Optuna hparams search
ArneBinder/pie-document-level pull request #123
Opened 2023-09-07 11:46 UTC by jk-tripathy

Can be merged once https://github.com/ArneBinder/pie-document-level/pull/108 is completed.

Hparam Seach can be run with: `python src/train.py model=token_classification_with_seq2seq_encoder_and_crf experiment=sciarg_adus_sam_paper hparams_search=full_sam_paper`

2023-09-07 12:27 UTC, ArneBinder requested changes
Initial feedback.

2023-09-07 12:27 UTC, ArneBinder commented on configs/hparams_search/full_sam_paper.yaml
> +      model.freeze_base_model: choice(true, false)
I think it makes sense to have a different hparams_search config for `freeze_base_model=true` and one for `false`. Freezing the base model will *require* additional parameters (e.g. in the seq2seqencoder) because the single linear classifier layer (+crf) should not be able to capture the relevant semantics for the task. This may not be the case when fine-tuning the whole base transformer model.

2023-09-07 12:30 UTC, ArneBinder commented on configs/hparams_search/full_sam_paper.yaml
> +      model.freeze_base_model: choice(true, false)
Also: the experiment config `sciarg_adus_sam_paper` is especially build (and we did already some hyperparameter search last year) for the case of `freeze_base_model=true`. But we tried just with `allenai/scibert_scivocab_uncased`. So, some slightly different hps (hyperparameters) may work better, but especially for the other models.

2023-09-07 12:30 UTC, jk-tripathy commented on configs/hparams_search/full_sam_paper.yaml
> +      model.freeze_base_model: choice(true, false)
Right that makes sense, ill make two separate files for the search

2023-09-07 12:39 UTC, jk-tripathy commented on configs/hparams_search/full_sam_paper.yaml
> +      model.freeze_base_model: choice(true, false)
> Also: the experiment config `sciarg_adus_sam_paper` is especially build (and we did already some hyperparameter search last year) for the case of `freeze_base_model=true`. But we tried just with `allenai/scibert_scivocab_uncased`. So, some slightly different hps (hyperparameters) may work better, but especially for the other models.

Right got it

2023-09-14 18:56 UTC, ArneBinder requested changes
I guess the values look fine (but I just glanced over them). But please add small descriptions to the beginning of the three new `hprams_search` config files describing what they are about  (and fix the spelling in `unfozen_trunc.yaml`). Also add a small description to this PR saying whats added so far (note that the other configs will be added via the other PR and do not need to be described here).

EDIT: Please try with the biggest model what batch size works before starting the full hparams search. Would be unfortunate if it breaks in the middle.

FYI I rebased the branch and also the respective branch in `pie-models`. Please update and `pip uninstall pie-models` & re-install from `requirements.txt`.

2023-09-14 18:56 UTC, ArneBinder commented on configs/hparams_search/frozen_full.yaml
> +      model.freeze_base_model: true
I guess single values (no range or choice) need to be defined just outside the `hydra` section (e.g. at the very bottom of the file).

2023-09-14 18:56 UTC, ArneBinder commented on configs/hparams_search/unfozen_trunc.yaml
> +      taskmodule.tokenizer_name_or_path:w: choice(allenai/scibert_scivocab_uncased, allenai/longformer-base-4096, allenai/longformer-scico)
remove the "w"

2023-09-19 13:14 UTC, jk-tripathy commented on configs/hparams_search/frozen_full.yaml
> +      model.freeze_base_model: true
got it

2023-09-19 13:14 UTC, jk-tripathy commented on configs/hparams_search/unfozen_trunc.yaml
> +      taskmodule.tokenizer_name_or_path:w: choice(allenai/scibert_scivocab_uncased, allenai/longformer-base-4096, allenai/longformer-scico)
ah my bad, ill change that

2023-09-20 21:48 UTC, jk-tripathy commented on configs/hparams_search/frozen_full.yaml
> +      model.freeze_base_model: true
i checked this btw, does not seem to matter where the param is defined

2023-10-20 11:12 UTC, ArneBinder requested changes
Some minor things.

2023-10-20 11:12 UTC, ArneBinder commented on configs/hparams_search/bert_frozen_with_seq2seq_enc.yaml
> +# python train.py -m hparams_search=conll2003_optuna experiment=conll2003
Replace with short description that gives the motivation (why do we need this?) and content (e.g. different bert variants + s2s encoder, because...) of this config and adjust the example command (also in the other configs)

2023-10-20 11:12 UTC, ArneBinder commented on configs/model/seq2seq_encoder/lstm.yaml
> +type: lstm
add a short description, e.g.
```suggestion
# two layer Bi-LSTM with dropout
type: lstm
```

2023-10-20 11:12 UTC, ArneBinder commented on configs/model/seq2seq_encoder/many_encoders.yaml
> +  type: tanh
add a short description (see lstm example), maybe say that `lin0` and `act0` are arbitrary identifiers, but its order matters (defines how the sequential is constructed)

2023-10-20 11:12 UTC, ArneBinder commented on configs/model/seq2seq_encoder/none.yaml
> +type: none
add short description (e.g. empty dummy encoder to use no sequence-to-sequence encoder at all)

2023-11-02 18:47 UTC, ArneBinder approved these changes

2023-11-02 19:50 UTC, merged