Tests to verify the dataset conversion for cdcp
ArneBinder/pie-document-level pull request #152
Opened 2023-10-05 15:09 UTC by idalr

In this PR, we test the `cdcp` dataset conversion logic; similar to what we did with `argmicro` in #137. 

Latest update:
17.10.23: Fixed according to review (7f41936), fixed lines and space (89d890b)

2023-10-17 10:24 UTC, ArneBinder requested changes
Thanks for the PR, I listed some issues that still need to be fixed. ~Also, please use the value that is currently used in `input.path` of the dataset config (`cdcp_base`) for `PIE_DATASET_PATH`. Because this is the one, that we use when executing experiments.~

EDIT: Sorry, I just noticed, that `PIE_DATASET_PATH` is not used at all.

2023-10-17 10:24 UTC, ArneBinder commented on tests/unit/dataset_builders/test_cdcp.py
>      if split == "train":
This (also the branch below) is never `True` because `split` is not provided as a method argument. Thus, `split` is just the *method itself* as it is defined above and will not be converted to the method return value. Please check with a debugger, if all code is really reached.

2023-10-17 10:24 UTC, ArneBinder commented on tests/unit/dataset_builders/test_cdcp.py
> +        assert len(document.propositions) == 3
`TextDocumentWithLabeledEntitiesAndRelations` should not have the attribute `propositions`. Please check the definition of that document type.

2023-10-17 10:24 UTC, ArneBinder commented on tests/unit/dataset_builders/test_cdcp.py
> +    if split == "train":
as above

2023-10-17 14:49 UTC, idalr commented on tests/unit/dataset_builders/test_cdcp.py
>      if split == "train":
fixed in 7f41936, by adding the argument `split` to the test

2023-10-17 14:49 UTC, idalr commented on tests/unit/dataset_builders/test_cdcp.py
> +    if split == "train":
Also fixed in 7f41936

2023-10-17 14:50 UTC, idalr commented on tests/unit/dataset_builders/test_cdcp.py
> +        assert len(document.propositions) == 3
Fixed in 7f41936. Use `entities` instead

2023-10-18 15:51 UTC, ArneBinder commented on tests/unit/dataset_builders/test_cdcp.py
> +    if split == "train":
It looks like `test_convert_to_textdocument_with_entities_and_relations` is still wrong.

2023-10-18 16:15 UTC, ArneBinder commented on tests/unit/dataset_builders/test_cdcp.py
> +    if split == "train":
fixed in [88cfd1b](https://github.com/ArneBinder/pie-document-level/pull/152/commits/88cfd1b6da34bf2e227cabf395cf1ec71d464172). But now, the branching is trivial and should be simplified.

2023-10-18 16:35 UTC, ArneBinder approved these changes

2023-10-18 16:35 UTC, merged