Fix conversion for aae2
ArneBinder/pie-document-level pull request #159
Opened 2023-10-19 15:51 UTC by idalr

We add relations between `MajorClaim`s and `Claim`s in the dataset `aae2` because the relations between these ADUs did not exist in the original dataset.

2023-10-23 11:16 UTC, idalr commented
In d5c7f5c and 47e658b, I propose two possible ways to convert the relations between `MajorClaim`s and `Claim`s:
1. `convert_aae2_claim_attributions_to_relations_with_all_majorclaims`
**example**: given 2 `MajorClaim`s and 2 `Claim`s, we build the relations: 
- `Claim`1 -> `MajorClaim`1 
- `Claim`2 -> `MajorClaim`1 
- `Claim`1 -> `MajorClaim`2 
- `Claim`2 -> `MajorClaim`2 

**pro**: every `MajorClaim` has `Claim`s that point directly to them. 
**con**: these many-to-many relations could be redundant.

2. `convert_aae2_claim_attributions_to_relations_with_main_majorclaim`
**example**: given 2 `MajorClaim`s and 2 `Claim`s, we build the relations: 
- `MajorClaim`2 \== `MajorClaim`1 
- `Claim`1` -> MajorClaim`1 
- `Claim`2` -> MajorClaim`1 

**pro**: less redundancy, every `Claim` and `MajorClaim` centralizes around one `MajorClaim`
**con**: we have to introduce a new type of relation: `semantically_same` (\==), which is bidirectional and non-argumentative; unlike existing relations in the corpus.

2023-10-23 14:46 UTC, ArneBinder requested changes
This has very good quality, thanks!

See some minor things below. Please also convert the comments with `TODO` to simple comments (in the tests; I think there is nothing more todo) and remove any code that is commented out.

EDIT: I think it would be nice to have single method for both approaches with a parameter `method: str` that could e.g. have values such as `"connect_first"` and `"connect_all"`, and depending on that value one or the other approach is used. Then, you can also parametrize the test method to have one for both cases:

```python
@pytest.mark.parametrize("method", ["connect_first", "connect_all"])
def test_convert_aae2_claim_attributions_to_relations(document, method):
    converted_doc = convert_aae2_claim_attributions_to_relations(document, method=method)
    # test general stuff
    ... 
    if method == "connect_first":
       ...
    elif ...
    else ...
```

2023-10-23 14:46 UTC, ArneBinder commented on src/document/conversion.py
> +                    score=DEFAULT_SCORE,
Don't set the score, so that the internal default value will be used (in fact it should be None, I will change this later in the implementation of `BinaryRelation`). Also in the two occurrences below.

2023-10-23 14:46 UTC, ArneBinder commented on src/document/conversion.py
> +DEFAULT_SCORE = 1.0
remove (see below)

2023-10-23 14:46 UTC, ArneBinder commented on src/document/conversion.py
> +ATTRIBUTIONS_TO_RELATIONS_DICT = dict({"For": "supports", "Against": "attacks"})
- rename to `DEFAULT_ATTRIBUTIONS_TO_RELATIONS_DICT`
- why is the dictionary (marked by `{` and `}`) wrapped again in `dict()`?

2023-10-23 14:46 UTC, ArneBinder commented on src/document/conversion.py
> +    document: BratDocumentWithMergedSpans,
Add the parameters:
 - `attributions_to_relations_mapping: Dict[str, str]] = DEFAULT_ATTRIBUTIONS_TO_RELATIONS_DICT`
 - `major_claim_label: str = "MajorClaim"
 - `claim_label: str = "Claim"`
 
 and use them in the method.

2023-10-23 14:46 UTC, ArneBinder commented on src/document/conversion.py
> +    document: BratDocumentWithMergedSpans,
Add the same parameters as for the other method and in addition `semantically_same_label`.

2023-10-23 14:46 UTC, ArneBinder commented on src/document/conversion.py
> +        majorclaims_list.pop(0)
```suggestion
        main_majorclaim = majorclaims_list.pop(0)
```

2023-10-25 14:27 UTC, idalr commented on src/document/conversion.py
> +                    score=DEFAULT_SCORE,
fix in db1b315

2023-10-25 14:28 UTC, idalr commented on src/document/conversion.py
> +DEFAULT_SCORE = 1.0
fix in db1b315

2023-10-25 14:28 UTC, idalr commented on src/document/conversion.py
> +ATTRIBUTIONS_TO_RELATIONS_DICT = dict({"For": "supports", "Against": "attacks"})
fix in db1b315

2023-10-25 14:28 UTC, idalr commented on src/document/conversion.py
> +    document: BratDocumentWithMergedSpans,
fix in db1b315

2023-10-25 14:28 UTC, idalr commented on src/document/conversion.py
> +    document: BratDocumentWithMergedSpans,
fix in db1b315

2023-10-25 14:28 UTC, idalr commented on src/document/conversion.py
> +        majorclaims_list.pop(0)
fix in db1b315

2023-10-25 15:12 UTC, idalr commented
@ArneBinder 
I have combined both approaches into a single method with a parameter `method: str` in a13e49a, then updated the tests accordingly in dfaee7a

2023-10-26 13:36 UTC, ArneBinder commented
> @ArneBinder I have combined both approaches into a single method with a parameter `method: str` in [a13e49a](https://github.com/ArneBinder/pie-document-level/commit/a13e49ab5ee6955853791bad9615175813f21677), then updated the tests accordingly in [dfaee7a](https://github.com/ArneBinder/pie-document-level/commit/dfaee7a447f14178f3b3370fde1a7d52a259e65c)

Thanks! I'll have a look.

2023-10-26 15:48 UTC, ArneBinder commented
This looks good. I still did some polishing and added that the major claims are sorted by their start positions, see my commits.

Final TODO: integrate that functionality into the `document_converts` in the config: [here](https://github.com/ArneBinder/pie-document-level/blob/main/configs/dataset/aae2_base.yaml#L20-L23) and [here](https://github.com/ArneBinder/pie-document-level/blob/main/configs/dataset/aae2_base.yaml#L24-L39). 

For the former, you first need to change it to use a processing Pipeline (as it is already done in the latter). You can just replace this:
```
      # just rename the layer
      spans: labeled_spans
      relations: binary_relations
```
by
```
      # cast to the correct type
      _target_: src.document.processing.Pipeline
      cast:
        _target_: src.document.processing.Caster
        document_type: pytorch_ie.documents.TextDocumentWithLabeledSpansBinaryRelationsAndLabeledPartitions
        field_mapping:
          spans: labeled_spans
          relations: binary_relations
``` 

This is semantically the same (just a bit more inefficient, but since `aae2` is not a large dataset, this is fine).

Then, you can add the step for adding the main claim relations to the pipeline. Note, that this will require to change some tests because we no get more relations when converting to `TextDocumentWithLabeledSpansAndBinaryRelations` or `TextDocumentWithLabeledSpansBinaryRelationsAndLabeledPartitions`!

2023-11-01 10:21 UTC, ArneBinder approved these changes
Thanks, this looks good! You can merge this (use "Squash and merge" below when CI is green again).

PS: I did one more minor change in c39d42d2f31ab967394b91d6cbcc909c93fb23fe.

2023-11-01 13:57 UTC, merged