postprocess sciarg cross-section annotations
ArneBinder/pie-document-level pull request #330
Opened 2024-12-18 13:59 UTC by idalr

This PR includes:
- a python script that takes a cross-section annotation file in `.csv` or `.xlsx` format (aka input format) and transforms it into a `JSON` file (aka output format).
   - The algorithm searches for the argument strings in the base text via regex, then obtains the start and end indexes of the string, taken into account if the strings are unique or not. When argument strings are not unique, a string index should be specified manually by the annotator.
- a folder with cross-section annotation files (by two annotators (@idalr and @alisakasha) and aligned annotation file (after both annotators agreed and resolved all annotations) in both formats.

Current version of the script takes the aligned annotation version of input to create output. However, one can define `texts_dir`, `input_path` and `output_path` to process different input files as long as the format is correct.

Important note:
- to read excel input .xlsx (instead of csv), the package `openpyxl` is required
- this also modifies `.gitignore` to *include* the content of `data/annotations/` to git versioning (note that the `data` directory for itself is *excluded*)

Usage:
just call the following which uses default parameters to reproduce the output: 
```
python src/data/prepare_sciarg_crosssection_annotations.py
```

TODOs:
 - [x] make all warnings go away when calling on the individual annotation files from @idalr and @alisakasha
 - [x] create output for the aligned annotation file and add both, the input and the result file, to the PR
 - [x] set defaults to reproduce output on aligned annotation file
 - [x] update this PR description with relevant information about: short explainer what this is about, script usage, and where the (already calculated) output is located

2024-12-18 16:53 UTC, ArneBinder requested changes
Thanks for the PR!

I tried to execute, but it seems some file paths are not correct:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/annotations/sciarg-abstracts/v0.9/without_abstract_annotations/'
```
EDIT: OK, when setting the paths like this it worked:
```
raw_anno_dir = "data/annotations/sciarg-abstracts/without_abstract_annotations/"
excel_dir = "data/annotations/sciarg-abstracts/cross-sect_xlsx/"
```

In addition to below comments, please address the following:
- [x] simplify: 
   - process only a single excel file (provided as parameter)
   - full paths for all path related parameters (no dependency between them)
- [x] use `argparse` 
- [x] use default values that work out-of-the-box when cloning this repo (assuming `openpyxl` is installed)
- [x] can we move to a format where we assume that there is a single sheet with the document id in the first column? we will probably switch to saving the (input) data as a simple csv to not rely on excel reading. 
- [x] Can you edit the excel files accordingly (move into one sheet and add the doc id to all rows)? 
- [x] Also, simply load all text files `{texts_dir}/{doc_id}.txt`  for all doc ids in the excel sheet and just raise an error if one file does not exist (instead of scanning the content of texts_dir and extracting the doc id from the file name). We may remove the folder `without_abstract_annotations` in favor of a folder containing *all* original text files. 
- [x] add a boolean parameter (argparse flag) that causes to not use `unsure` annotations
- [x] maybe apply `.strip()` on the `span_string` before searching it to remove any accidentally added whitespace? Just if this removes `This span does not exist in text` errors.

2024-12-18 16:53 UTC, ArneBinder commented on src/data/read_sciarg_crosssection_xlsx_to_json.py
> +        f.close()
use 
```
with open(...) as f:
  ...
```

2024-12-18 16:53 UTC, ArneBinder commented on src/data/read_sciarg_crosssection_xlsx_to_json.py
> +    """
move loading of the texts and saving of the results into this method. It should have parameters such as `texts_dir: str`, `excel_path: str`, `output_dir: str` and `None` as result type

2024-12-19 01:46 UTC, idalr commented on src/data/read_sciarg_crosssection_xlsx_to_json.py
> +        f.close()
fixed in 5201fa9

2024-12-19 01:46 UTC, idalr commented on src/data/read_sciarg_crosssection_xlsx_to_json.py
> +    """
fixed in 5201fa9

2024-12-19 02:02 UTC, idalr commented
Update:
- Changed python file name from `...xlsx_to_json.py` to `...csv_to_json.py`
- Created `test_file.csv` as mock input (i.e., a CSV with `doc_id` as the first column and including all cross-section annotations by one annotator). I will edit Excel files according to this format when we agree that the Excels are ready.
- Applied `.strip()`, but some of the current `This span does not exist in text` errors must have come from typos or spans were not properly copied.

Next steps:
- I am not sure what to define as default values for some argparse, since we might still move files and folders around?
- Recheck all spans and make sure there will be no typos.
- Still need to decide what to do with non-unique spans.
- @ArneBinder Could you please also check if the [current JSON output](https://github.com/ArneBinder/pie-document-level/blob/read_sciarg_cross-section_xlsx_to_json/data/annotations/sciarg-abstracts/test_file.json) is easy for you to use? Or, if you prefer a different data structure.

2024-12-19 13:06 UTC, ArneBinder commented
Thanks a lot, that looks quite nice! Also the write-up above (https://github.com/ArneBinder/pie-document-level/pull/330#issuecomment-2552617316).

I did some more polishing (especially in https://github.com/ArneBinder/pie-document-level/pull/330/commits/fe8c1eec62e6e19ae1e263af0ba5d6a1a454b421), adjusted the output format, renamed the script and swapped the semantic of the `unsure` parameter. Regarding the remaining next steps:

> I am not sure what to define as default values for some argparse, since we might still move files and folders around? 

makes sense, we will wait for the gold abstract annotations

> Still need to decide what to do with non-unique spans.

we may add another columns like `head_string_idx` and `tail_string_idx` to the excel where we put the index if the string is not unique 

I think, for now the code is fine. But please have a look at the recent changes and try to understand them. If you have any questions, don't hesitate to ask :)

EDIT: However, if you still notice any error or sth you would improve, just do so.

2024-12-25 23:03 UTC, idalr commented
In 7659e12, I added solutions to non-unique spans as previously discussed ("via additional columns head_idx and tail_idx that are taken into account if not empty"), as well as two new warnings (i.e., "1) column is not empty, but span is unique or 2) span not unique, but column is empty") and tested them.
Unfortunately, now the head_idx and tail_idx columns (now named 'head string index' and 'tail string index') are necessary in the input file.

2024-12-27 15:39 UTC, ArneBinder approved these changes
Thanks for the adjustments, this looks good!

2025-01-02 15:01 UTC, ArneBinder commented
@idalr I ran the script locally and got a different output than the one you added. I also added a test that checks for that in [this commit](https://github.com/ArneBinder/pie-document-level/pull/330/commits/3750da034aeb49c129a29e7668216302a000d8fb) which reproduces my results (see e.g. [here](https://github.com/ArneBinder/pie-document-level/actions/runs/12584042838/job/35072844585?pr=330)). Can you investigate what's wrong there and fix it?

EDIT: It is not very good visible in the test log, but it seems that the start and end indices are shifted by one. Also, `null` entries seem to be handled differently.
EDIT2: I also added a sanity check that the offsets are correct in [this commit](https://github.com/ArneBinder/pie-document-level/pull/330/commits/30103da7287d26f6b32ae0ea437bd01bf75159f1). When I run it locally with this check, it (the "new" offsets) seems to be fine. Can you re-run the script at your end to check that the offsets are fine there, too? If this is the same, I guess there is an issue with reading the raw text files (strangely adding a character to the front in any way?).
EDIT3: I added `get_texts_from_pie_dataset` method in https://github.com/ArneBinder/pie-document-level/pull/330/commits/c31d923cd7d1ea41b98dde4a1c6048aa65a44925, can you try using this instead of  `get_texts_from_directory` (this was the original way of loading the texts) and check locally at your side if this produces the offsets required for the tests at Github CI?

2025-01-02 21:08 UTC, idalr commented
I checked issues in the [comment above](https://github.com/ArneBinder/pie-document-level/pull/330#issuecomment-2567907805). I think what might have caused the issues is that **the output files were outdated**.
- Because `.gitignore` doesn't allow me to add files in `data` directory, so far, I always had to upload input and output files separately while I kept editing code minorly. Then, I forgot that I needed to generate new output files and also upload them.
- In commit 1d25238, I switched the order of deleting empty columns to after filtering unsure. Otherwise when the "unsure" column is empty, then `KeyError` appears because there would be no more "unsure" column to filter.
- The current output files (f13cf76, 785cde1, 66dbf50) in the last upload also include unsure annotations (for individual annotations only; there shouldn't be unsure in aligned annotation). The `pytest` hasn't so far.
- Now, locally, I re-generated all output files again and ran the test (both with and without `--including-unsure`). It all passed.

Trials with `get_texts_from_pie_dataset`:
- I re-generated all outputs locally and passed all tests in both unsure and no-unsure conditions.

What I haven't figured out:
- in my current `aligned_output.json`, all `head_span_idx` outputs of `A34` for shifts one position left (e.g., from `[4717,4859]` to `[4716,4858]`, etc.), from my former output (that in commit 66dbf50). I assume this is the offset issue that you are talking about? 
- However, I couldn't manage to reproduce the former output anymore; everytime now I can only produce the new offsets.

EDIT: perhaps, one of us can add the updated output files and re-test it again? Maybe we should include both unsure and no-unsure outputs for individual annotations as well?

2025-01-02 22:44 UTC, ArneBinder commented
Thanks for the investigation!

> in my current aligned_output.json, all head_span_idx outputs of A34 for shifts one position left (e.g., from [4717,4859] to [4716,4858], etc.), from my former output (that in commit https://github.com/ArneBinder/pie-document-level/commit/66dbf503b32401d227316b1198f8b03a1bb092e6). I assume this is the offset issue that you are talking about?

yes, I think so. 

> perhaps, one of us can add the updated output files and re-test it again? Maybe we should include both unsure and no-unsure outputs for individual annotations as well?

Can you do this? But I think just having no-unsure is still fine.

> Because `.gitignore` doesn't allow me to add files in data directory, so far, ...

OK, sounds annoying, I think it makes sense then to exclude the subdirs of `data`  from `.gitignore` again that contain committed files (`data/annotations/sciarg-abstracts` and `data/annotations/sciarg-cross-section`). Can adjust the `.gitignore` file accordingly (see e.g. [this explanation about negating patterns](https://linuxize.com/post/gitignore-ignoring-files-in-git/#negating-patterns))?

2025-01-03 14:12 UTC, ArneBinder requested changes
Thanks for the adjustments!

Remaining:
 - [x] the [diff for the .gitignore file](https://github.com/ArneBinder/pie-document-level/pull/330/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) contains the whole file, but you added just one line, I guess? Can you adjust that the diff shows correctly what was changed? In general, it is a good idea to check the complete diff at Github 1) to cleanup unnecessary changes and 2) to describe all changes in the PR description when a PR seems to be ready.
- [x]  are the files in `data/annotations/sciarg-cross-section/test` still needed? If not, please remove them.
- [x] add to the PR description: 
   - short description of the (algorithmic) approach ("search for the argument strings in the base text via regex and ...")
   - mention that (and how) the .gitignore file is changed

2025-01-04 16:41 UTC, ArneBinder approved these changes

2025-01-04 16:46 UTC, merged