Create tests for simple transformer text classification
ArneBinder/pie-document-level pull request #43
Opened 2023-05-17 14:49 UTC by akashkumar25

2023-06-06 14:40 UTC, ArneBinder requested changes
Looks very good! Just some minor remarks. Can you also rename `pre_prepared_taskmodule` to `unprepared_taskmodule`?

EDIT: Can you also integrate [the documentation](https://github.com/ArneBinder/pie-document-level/issues/29#issuecomment-1576738842) as comments to the respective fixtures / tests?  E.g.

```python
@pytest.fixture(scope="module", params=CONFIGS_DICT.keys())
def config(request):
    """
    This fixture is defined with the @pytest.fixture decorator and is used to provide a configuration dictionary (config) to other tests.
    It uses the CONFIGS_DICT dictionary to retrieve the configuration based on the parameter passed to the fixture (request.param).
    """
    return CONFIGS_DICT[request.param]
```

EDIT2: Maybe shorten / rewrite the texts a bit. For the above example this should be sth like: "This fixture yields the config dictionaries from the CONFIGS list. It is parametrized by the serialized configs to produce clean test case identifiers, e.g. `test_encode_input[max_length=8]`." Try to name the reasoning behind the code ("clean / readable test configuration") instead of mentioning whats directly derivable from the code ("is defined with the ... decorator", "It uses the CONFIGS_DICT..."), i.e. keep it concise as much as possible (if you think there does not happen sth that needs explanation, do not write a comment at all. But maybe then you can also write, why nothing else is happening there ;) E.g. "We do not test for xxx because it is already done in yyy ...").

2023-06-06 14:40 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    assert pre_prepared_taskmodule is not None
```suggestion
    assert pre_prepared_taskmodule is not None
    assert not pre_prepared_taskmodule.is_prepared
```

2023-06-06 14:40 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    pre_prepared_taskmodule._post_prepare()
```suggestion
    # this calls _prepare(documents) and then _post_prepare()
    pre_prepared_taskmodule.prepare(documents)
```

2023-06-06 14:40 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +def test_post_prepare(taskmodule):
```suggestion
def test_prepare(taskmodule):
```

2023-06-08 13:31 UTC, ArneBinder requested changes
some minors

2023-06-08 13:31 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    - Prepares the task module for the given documents.
```suggestion
    - Prepares the task module with the given documents, i.e. collect available label values.
```

2023-06-08 13:31 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    - Generates encoded inputs for a specific document without associated targets.
```suggestion
    - Generates input encodings for a specific task from a document, but without associated targets.
```

2023-06-08 13:31 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    - This can be created with model_predict_output fixture above.
What does "This" refer to? Please improve that sentence.

2023-06-08 13:31 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    - Converts model outputs into human-readable named annotations.
```suggestion
    - Converts the inputs (task_encoding_without_targets) and the respective model outputs (unbatched_outputs) into human-readable  annotations.
```

2023-06-12 10:50 UTC, ArneBinder commented on tests/unit/taskmodules/test_simple_transformer_text_classification.py
> +    - This can be created with model_predict_output fixture above.
fixed in 5903433143d33cb8e8d3dc70b9b3d10c24b5f314

2023-06-12 11:00 UTC, ArneBinder requested changes
I noticed one important thing, see below.

2023-06-12 11:00 UTC, ArneBinder commented on src/models/transformer_text_classification.py
> +from pytorch_ie.core import PyTorchIEModel
Is this whole file still necessary? Can you just use `TransformerTextClassificationModel` from pytorch-ie in the `model_predict_output` fixture? We should only add code that is really necessary to not clutter the codebase. But please test if the fixtures is working by using it in the `unbatched_outputs` fixture:
```
@pytest.fixture(scope="module")
def unbatched_outputs(taskmodule, model_predict_output):
   ...
```

2023-06-12 11:27 UTC, akashkumar25 commented on src/models/transformer_text_classification.py
> +from pytorch_ie.core import PyTorchIEModel
No its not necessary, I have made the changes and unbatched_outputs fixture is working with it. Should I remove the this model file?

2023-06-12 11:59 UTC, ArneBinder commented on src/models/transformer_text_classification.py
> +from pytorch_ie.core import PyTorchIEModel
ok, cool. yes, please remove it. And also please remove `model_predict_output` again from the `unbatched_outputs` fixture, that was just meant to test locally that `model_predict_output` works.

2023-06-22 10:12 UTC, akashkumar25 commented on src/models/transformer_text_classification.py
> +from pytorch_ie.core import PyTorchIEModel
I have removed the transformer_text_classification.py file and model_predict_output from unbatched_outputs fixture.

2023-06-22 12:02 UTC, ArneBinder commented
This is integrated upstream (see https://github.com/ChristophAlt/pytorch-ie/pull/282), we keep this here for documentary reasons.

2023-06-22 12:02 UTC, closed without merging