Add .md files on corpora
ArneBinder/pie-document-level pull request #96
Opened 2023-08-11 14:27 UTC by idalr

In this PR, we added the corpora documentation on our six corpora: AAE2, AbsTRCT, ArgMicro, CDCP, SciArg, and SciDTB-argmin.

In each markdown file, we provide the description of the corpus, general information, external resources, example, its components and relations, data structure, and collected statistics (see [metrics](https://github.com/ArneBinder/pie-document-level/tree/main/configs/metric)).

In `CONCEPTS.md`, we also provide some concept explanations, regarding argument mining, annotation, components, etc.

2023-08-14 14:56 UTC, ArneBinder requested changes
Thanks a lot for this extensive write up! There is already a lot of good content in it. Still, I added a lot of comments, especially to the first file (most of them apply also for the remaining ones, so please handle them everywhere where you think it makes sense). Please don't be overwhelmed by that, it looks quite good for the first version of this PR.

Some additional general notes:
 - add a small description to this PR: what it does and why (if you are not sure about it, you can write an initial proposal and ping me with e.g. `@ArneBinder did you mean this?` at the end.)
 - execute `pre-commit run -a` before pushing any files to github. The command should finish without complains. This also runs on GitHub via continuous integration (CI) workflows. Have a look at the small red cross at the bottom of the PR, that should become a green check mark when you have pushed the fixed files.
 - make the folder `AM corpora` a subfolder of another one (e.g. `AM documentation/corpora` or `AM knowledge base/corpora`). We will extend on that later on, e.g. with a `models` or `approaches` folder.
 - add sub-headings: see https://www.markdownguide.org/basic-syntax/#headings
 - add some more features that we can later use to compile an overview table, e.g.
 	- `text domain`: scientific, ...
   	- `text granularity` (maybe chose a better name): Is this full text, just abstracts, or paragraphs? An indicator is what components from which **parts of the text** are connected by argumentative relations in the dataset.
 - see the dataset PRs for further inspiration for what information can be added: https://github.com/ArneBinder/pie-document-level/pulls?q=is%3Apr+is%3Aclosed+label%3A%22new+dataset%22

If anything I wrote is ambiguous, does not make any sense to you, etc, please let me know!

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +	- type: tree
What does the `#` or `%` mean? Is it just to mark indentation? If so, please just indent these lines accordingly.

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +- AAEC (Stab and Gurevych, 2017) contains student essays. There are two types of data: essay-level and paragraph-level (Eger et al., 2017). A stance for a controversial theme is expressed by a MajorC
- quotation marks should be written just as quotes: `"shell"` instead of `´´shell´´`. I think some other quotation marks are missing (e.g. "on the other hand")?
- if there are concepts in the main texts that are no real words (e.g. `MainClaim`) or, in general, have a certain meaning defined here (e.g. `Premise`), put them in tics to mark them as code (see here: https://www.markdownguide.org/basic-syntax/#code)
- please add links to the references (see e.g. this [markdown how-to](https://www.markdownguide.org/basic-syntax/#links)) either directly in the text or as a list after the text

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +	- Segment-based spans: No
can you put this in a markdown-table? 
 - this describes the syntax: https://www.codecademy.com/resources/docs/markdown/tables
 - but there are also table generators, e.g. https://www.tablesgenerator.com/markdown_tables

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +		- note: list
This is not very well readable. To improve, you could:
 - remove everything that comes from the [BRAT standoff format](https://brat.nlplab.org/standoff.html), just reference their documentation
 - use the document type (e.g. see `BratDocument` or `BratDocumentWithMergedSpans` from [here](https://huggingface.co/datasets/pie/brat/blob/main/brat.py)) instead of the dictionary representation to describe the format
 - do not list examples per field, but give one single example at the end
 - in general: keep it short as best as possible, try to reference external information if available

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +- via evaluate_documents
Can you add the exact command you used to get this? So that we can re-calculate, in the case that anything changes / is fixed in the future.
```suggestion
- via evaluate_documents: `python src/evaluate_documents.py ...`
```

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +
Please also replace with markdown tables. I improved the logging a bit, if you pull the latest changes, the statistics are also written into a markdown file (the exact location is written on the console) whose content you can copy.

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +	- Segment-based spans: No
Can you also add short definitions (maybe approx. one sentence) for the individual types? I'm not 100% sure if this should be in a table or just in an indented bullet list, decide for yourself what looks better.

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +		- note: list
Could you also add a figure that shows a data example, maybe take a screenshot from the dataset paper?

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/abstrct.md
> +- AbstRCT (Mayer et al., 2020) includes abstracts of randomized controlled trials (RCTs) from the MEDLINE database.3 MajorClaim, Claim, and Evidence components, along with Support, Attack, and Partia
Do the components include or exclude "shell language" (see `corpora/aae2.md`)?

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/argmicro.md
> +- aka MTC (Peldszus and Stede, 2016) is based on Freeman’s theory of the macro-structure of arguments (Freeman, 2011) and incorporates the ideas of Toulmin (Toulmin, 2003) into diagramming techniques
What does it mean to "pre-process the Add relations similarly to Kuribayashi et al. (2019)"?

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +- AAEC (Stab and Gurevych, 2017) contains student essays. There are two types of data: essay-level and paragraph-level (Eger et al., 2017). A stance for a controversial theme is expressed by a MajorC
The author is called "Morio", not "Mario".

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/aae2.md
> +
Also compare with Table 1 of Morio et al. (2022). Are there any differences? if so, 
 - first, please list them. 
 - Then, try to explain them (we can also look into this together).

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/sciarg.md
> +- enriching Dr. Inventor corpus, consisting of 40 publications from computer graphics, with argumentative information
This is a bit short, can you extend this?

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/terms explained.md
> +	- graph: structure where nodes interlink in different directions, allowing transitive relations, reentracies, etc.
Just as a side note: Would be interesting to know if the argumentative graphs are DAGs, directed acyclic graphs, or if they are allowed to contain cycles. Would it be a problem if they contain cycles?

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/terms explained.md
> +- relation density: average value of $N_r/(N_c − 1)$
oh, cool, I did not know that it is possible to have inline latex-math!

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/terms explained.md
> +		- limited to TESTIMONY or REFERENCE
Everything that is specific to the dataset should just be mentioned in the respective markdown file (e.g. `argmicro.md`)

2023-08-14 14:56 UTC, ArneBinder commented on AM corpora/terms explained.md
> +In Mario et al. 2022
Rename the file to `CONCEPTS.md` (in capital letters to differenciate from actual dataset discriptions).

2023-08-14 15:06 UTC, ArneBinder commented on AM corpora/terms explained.md
> +In Mario et al. 2022
Also, link to this file from the dataset files where it is helpful to know about the concepts.

2023-08-17 15:04 UTC, idalr commented on AM corpora/aae2.md
> +	- type: tree
Fixed in 54927d8 for clarity. Originally # refers to count and % refers to percent.

2023-08-17 15:05 UTC, idalr commented on AM corpora/aae2.md
> +- AAEC (Stab and Gurevych, 2017) contains student essays. There are two types of data: essay-level and paragraph-level (Eger et al., 2017). A stance for a controversial theme is expressed by a MajorC
fixed in 54927d8

2023-08-17 15:06 UTC, idalr commented on AM corpora/aae2.md
> +	- Segment-based spans: No
fixed in 54927d8. Arranged in a table, with explanation in bullet list below

2023-08-17 15:10 UTC, idalr commented on AM corpora/aae2.md
> +		- note: list
improved in cc8debe.
- add reference to BRAT standoff format
- not sure if what I took from `BratDocument` in `brat.py` makes sense. If not, please let me know
- create one data sample in a table

2023-08-17 15:10 UTC, idalr commented on AM corpora/aae2.md
> +- via evaluate_documents
fixed in https://github.com/ArneBinder/pie-document-level/commit/54927d84d728be98b880aa5da4e755b6be0aba4a

2023-08-17 15:16 UTC, idalr commented on AM corpora/aae2.md
> +
improved in cc8debe and 2026e10:
- arranged in md tables
- included stats from the whole dataset (402 docs) and when separated as train, test, valid datasets

further work:
- compare and list out differences between these stats and in the original paper (Stab&Gurevych '17), and explain the difference
- add new statistics: `relation_argument_distances` and `relation_argument_tokens_distances`

2023-08-17 17:07 UTC, ArneBinder commented on AM corpora/aae2.md
> +		- note: list
Looks good in general, regarding the "Data fields" section: You could rename that to e.g. "Document Structure" or "Data Structure" and separate the fields into "data fields" (context, filename) and annotation layers (spans, relations, ...). Then, you can name the python type + default, if available, for all data types and the annotation type + target for all annotation layers.

2023-08-17 17:12 UTC, ArneBinder commented on AM corpora/aae2.md
> +
As discussed, I think it is enough to have the statistics for the splits as they are in the original dataset. Can you use the commands that we tried in our meeting to re-create the tables in such a way?

2023-08-17 17:19 UTC, ArneBinder commented
I commented to all the issues that you already have handled. I kept them unresolved for now, because I think they also apply to the other dataset documents.

2023-08-25 16:31 UTC, idalr commented on AM corpora/aae2.md
> +		- note: list
improved in 6c597370b5319028a8a5639b0df123930e164aae

2023-08-25 16:40 UTC, idalr commented on AM corpora/aae2.md
> +
Regarding statistics in datasets:
- the statistics comparison section in `aae2.md`. Numbers are approximately aligned but not completely.
- I haven't proceed with other datasets, but I saw discrepancies between 1) statistics in the original paper, 2) statistics reported by Morio et al., and also 3) what we evaluate ourselves via commands
- I couldn't pull out the statistics of the whole dataset from `abstrct` and `cdcp` with `+dataset.create_validation_split._enabled_=false +dataset.create_test_split._enabled_=false`. I assume the structure of dataset and `<dataset>_prepared.yaml` are a bit different. I tried what I though would work, but didn't manage.

2023-08-25 16:42 UTC, idalr commented on AM corpora/argmicro.md
> +- aka MTC (Peldszus and Stede, 2016) is based on Freeman’s theory of the macro-structure of arguments (Freeman, 2011) and incorporates the ideas of Toulmin (Toulmin, 2003) into diagramming techniques
I left this part out in the recent commit (d2b27a4193a1c5448ad10f1666483e7382b34a7f), as this was the part on how Morio et al. were processing `argmicro` for their own experiment

2023-08-25 16:42 UTC, idalr commented on AM corpora/sciarg.md
> +- enriching Dr. Inventor corpus, consisting of 40 publications from computer graphics, with argumentative information
extended in recent commit a59c87a6eb3d23fdf51be6a0bcc5c811f622d634

2023-08-25 16:44 UTC, idalr commented on AM corpora/abstrct.md
> +- AbstRCT (Mayer et al., 2020) includes abstracts of randomized controlled trials (RCTs) from the MEDLINE database.3 MajorClaim, Claim, and Evidence components, along with Support, Attack, and Partia
You're right. In `abstrct`, they left out the "shell" language

2023-08-25 16:45 UTC, idalr commented on AM corpora/terms explained.md
> +		- limited to TESTIMONY or REFERENCE
fix in recent commit 6c597370b5319028a8a5639b0df123930e164aae

2023-08-25 16:46 UTC, idalr commented on AM corpora/terms explained.md
> +In Mario et al. 2022
in 6c597370b5319028a8a5639b0df123930e164aae:
- renamed the file
- linked concepts from \<dataset>.md to this file

2023-08-25 16:57 UTC, idalr commented on AM corpora/terms explained.md
> +	- graph: structure where nodes interlink in different directions, allowing transitive relations, reentracies, etc.
At least in `sciarg` it was explicitly stated that they were DAGs. But, nothing is indicated in `cdcp` and `abstrct` - where they were also graphs. None of the papers discussed argumentative cyclic graphs so far.

However, Stab and Gurevych (2017) wrote something like graphs indicated complexity and divergence in arguments (pp.626-627)

2023-08-28 09:26 UTC, ArneBinder commented on AM corpora/terms explained.md
> +	- graph: structure where nodes interlink in different directions, allowing transitive relations, reentracies, etc.
Ok, thanks for the investigation.

2023-08-28 13:56 UTC, ArneBinder requested changes
We are getting close! This was already a nice read.

Some missing points:
- add new point "pre-defined splits" (e.g. `train`: *num of train docs*, `test`: *num of test docs*; may be just `none` as in the case of sciarg), maybe below original dataset statistic
   - the statistics that you collected should be for these splits 
- add a new point "ADUs contain shell language" (yes or no) (below "segment-based spans", should be the same value as that, but to have it written down explicitly makes it a bit more visible)
- add a new point "text based or token based" (I think only scidtb_argmin is token based, the other datasets should be text based)
- please also add label count statistics for the relations (you can copy the `count_entity_labels.yaml` config and adjust it to collect the labels of the relations instead of the entities)

This is also required, but we should do this in one or multiple follow-up PRs because this is already quite big:
- next to component and relation counts, the percentage would be interesting
- add new point "preprocessing in Morio et al" (how did the authors process the data? e.g. splits, adjusting of components / relations, ...)
- screenshots of examples (such as the pdfs in argmicro)

2023-08-28 13:56 UTC, ArneBinder commented on AM_documentation/corpora/CONCEPTS.md
> +- on the other hand, "shell" language, or minimal unit span, has minimum boundaries and discriminates argumentative component parts from non-argumentative parts in the clause/sentences.
This needs some clarification (this is very bad written in Morio et al.). As I understand it, `segment-based spans` means that the text is *segmented* into spans that cover the whole text (i.e. when merging the spans it reproduces the original text). As a result, this also contains `shell` language (that are mostly rhetorical discourse markers such as "therefore", "on the other hand", etc) or other non-argumentative content. In contrast, `non-segment-based spans` do not need to cover the whole input text and should only consist of argumentative content (in the context of ADUs/AM).

Does this make sense or do you see any inconsistencies?

2023-08-28 13:56 UTC, ArneBinder commented on AM_documentation/corpora/CONCEPTS.md
> +"a joint of two or more adjacent elementary discourse units When two adjacent EDUs are argumentatively relevant only when taken together, these EDUs are first connected with one joint EDU node by seg
Is this really about joint "EDUs", not "ADUs"? Compare example "en/micro_b001" from the argmicro corpus. Here it looks like multiple ADUs participate jointly in a support relation. 

Is `Joint` a "general" concept at all? Or specific to the argmicro corpus?

Or is this the same as a `linked argument` (see section "convergent argument" above)?

2023-08-28 13:56 UTC, ArneBinder commented on AM_documentation/corpora/aae2.md
> +- Argument Annotated Essays Corpus (AAEC) ([Stab and Gurevych, 2017](https://aclanthology.org/J17-3005.pdf)) contains student essays. There are two types of data: essay-level and paragraph-level ([Eg
"There are two types of data: essay-level and paragraph-level" what does this mean? What is essay-level / paragraph-level data?

2023-08-28 13:56 UTC, ArneBinder commented on AM_documentation/corpora/aae2.md
> +- `MajorClaim` is the root node of the argumentation structure and represents the author’s standpoint on the topic. Essay bodies either support or attack the
How is the `MajorClaim` defined if the current structure has multiple "roots" (above it is written that only 73% of the entries are trees)? Is it each root of the subtrees then?

2023-08-28 13:56 UTC, ArneBinder commented on AM_documentation/corpora/argmicro.md
> +  - definition: "targeting an edge and thereby challenging the acceptability of the inference from the source to the target node"
The entries of the table do not match the entries of the list (especially `seg` and `sup`, see [here](https://huggingface.co/datasets/DFKI-SLT/argmicro/blob/main/argmicro.py#L37)). What's about that and the missing items them?

2023-09-06 16:14 UTC, idalr commented on AM_documentation/corpora/CONCEPTS.md
> +- on the other hand, "shell" language, or minimal unit span, has minimum boundaries and discriminates argumentative component parts from non-argumentative parts in the clause/sentences.
As we spoke last week, in commit de8352b, I added `segment-based span`, `non-ADUs`, and `shell language` in every corpus file; also defined `segment-based spans` and `shell language`  in the CONCEPTS.md file.

2023-09-06 16:23 UTC, idalr commented on AM_documentation/corpora/CONCEPTS.md
> +"a joint of two or more adjacent elementary discourse units When two adjacent EDUs are argumentatively relevant only when taken together, these EDUs are first connected with one joint EDU node by seg
corrected in de8352b.
`JOINT` is indeed the concept in ArgMicro although this is similar to `parts_of_same` in SciArg. This is NOT a linked argument, as I thought it was. `JOINT` is in the EDUs level - supposedly when a text is separated by punctuation. The given example in the guideline is EDU1 = [The building is contaminated by asbestos.] and EDU2 = [Through and through!]

2023-09-06 16:27 UTC, idalr commented on AM_documentation/corpora/aae2.md
> +- Argument Annotated Essays Corpus (AAEC) ([Stab and Gurevych, 2017](https://aclanthology.org/J17-3005.pdf)) contains student essays. There are two types of data: essay-level and paragraph-level ([Eg
elaborated in de8352b.
According to Stab & Gurevych, the diagrams of `Claim` and `Premise` are always completed in a paragraph. Therefore, when training and predicting, it is possible to feed data to a model by paragraph, as well as by essay.

2023-09-06 16:31 UTC, idalr commented on AM_documentation/corpora/aae2.md
> +- `MajorClaim` is the root node of the argumentation structure and represents the author’s standpoint on the topic. Essay bodies either support or attack the
elaborated in de8352b.
From what I understand so far, each essay is not a complete tree because they did not explicitly annotate the relation between `Claim` and `MajorClaim` and between claims in the same paragraph. Please see the Example section in the document.

2023-09-06 16:35 UTC, idalr commented on AM_documentation/corpora/argmicro.md
> +  - definition: "targeting an edge and thereby challenging the acceptability of the inference from the source to the target node"
elaborated in de8352b.
There were some changes in statistics that Morio et al. made, including this.
- First, they worked from the ADUs level; therefore, omitting 'seg' and 'joint' with are non-argumentative relations between EDUs and between EDUs and ADUs.
- Second, they removed `add` by merging ADUs that had `add` relations together.

2023-09-06 16:42 UTC, idalr commented on AM_documentation/corpora/CONCEPTS.md
> +- on the other hand, "shell" language, or minimal unit span, has minimum boundaries and discriminates argumentative component parts from non-argumentative parts in the clause/sentences.
I couldn't find the way to comment on the top comment...so, please allow me to add comments here:
In the recent commit (de8352b), I also added these new points:
- "pre-defined splits"
- "text-based or token-based"
- "contains ADUs"
- "contains shell language"
- "pre-processed by Morio et al." (only if needed)
- "example" (screenshot of example)
- column of percentage of components and relations, next to Morio et al.'s statistics
- `count_relation_labels` under "Collected Statistics" section - and also displayed statistics according to pre-defined split (if exists)

2023-09-07 12:52 UTC, ArneBinder commented on AM_documentation/corpora/aae2.md
> +- Argument Annotated Essays Corpus (AAEC) ([Stab and Gurevych, 2017](https://aclanthology.org/J17-3005.pdf)) contains student essays. There are two types of data: essay-level and paragraph-level ([Eg
Ah ok, thanks for the clarification!

2023-09-07 14:13 UTC, ArneBinder commented on AM_documentation/corpora/CONCEPTS.md
> +- on the other hand, "shell" language, or minimal unit span, has minimum boundaries and discriminates argumentative component parts from non-argumentative parts in the clause/sentences.
fyi regarding comments to the top comment: you can just add a comment to the very bottom of the PR (below the checks and merging section)

2023-09-12 11:09 UTC, ArneBinder approved these changes

2023-09-12 12:48 UTC, merged

2023-09-14 09:12 UTC, ArneBinder commented
Thanks a lot, @idalr!